### ISSUE TITLE
'Method not found: RestSharp.IRestRequest RestSharp.RestRequest.AddFile' dependency issue

### ISSUE THREAD

**Issue by NicMacRoy** [docusign/docusign-csharp-client#156] opened 2017-12-06 18:40 UTC
Integrating our application with the Docusign API and I keep receiving this issue when trying to send a individual document from our application. Here is the trace that I receive the error from:

`    string accountId = loginApi(username, password, integratorKey);`
Then in the loginAPI method:
`        LoginInformation loginInfo = authApi.Login();`

calling this method returns the error seen in the title.

We are using these packages:
Docusign.esign.DLL V2.1.8
RestSharp v106.1.0
RestSharpSigned v105.2.3
BouncyCastle v1.8.1

All the dependencies match for the Docusign API package but I'm not sure if having both RestSharp and RestSharpSigned may be confusing the LoginAPI method to call the correct method since Docusign uses RestSharpSigned. Anybody else encounter this issue?

**Comment by swilson361** [comment] 2018-01-12 08:40
Also experiencing this. Any news?

**Comment by leoseccia** [comment] 2018-01-16 13:18
How are you including the double reference to RestSharp?

Have you got something like this in your app.config?

      <dependentAssembly>
        <assemblyIdentity name="RestSharp" publicKeyToken="598062e77f915f75" culture="neutral" />
        <codeBase version="100.0.0.0" href="DocuSignRestSharp.dll" />
      </dependentAssembly>

**Comment by NicMacRoy** [comment] 2018-01-18 00:27
As docusign requires the package of RestSharpSigned instead of RestSharp, when you have integrate Docusign it doesn't seem to phase the fact that RestSharp is already included in the project and installs RestSharpSigned anyways. . Currently the only work around I found was to get rid of RestSharp and only use RestSharpSigned. Works like a charm if this is the case.

This isn't a permanent fix as every package that has a dependency of RestSharp doesn't work temporarily, but at least gets the ball rolling on integrating Docusign.

**Comment by leoseccia** [comment] 2018-01-18 10:12
I had the same issue so I kept the (custom/compiled in house) RestSharp library used by our application as RestSharp.dll, downloaded the signed version needed by Docusign and renamed it to DocuSignRestSharp.dll, ensured it got copied to output directory, put the code snippet from my last reply in the app.config and it all works as expected.

**Comment by Cloudmersive** [comment] 2019-06-15 03:35
Why is this issue closed?  This is still broken!

**Comment by LarryKlugerDS** [comment] 2019-06-16 08:52
re-opened.

**Comment by LarryKlugerDS** [comment] 2019-06-30 13:57
@all, @Cloudmersive , @leoseccia    What is the best description of this issue? 
"The C# SDK is using RestSharpSigned but it's older than the current RestSharp and doesn't include RestSharp.RestRequest.AddFile" or something different?

Please provide a concise explanation of the issue and suggested fix.

Thanks,
Larry

**Comment by mattscully** [comment] 2019-08-02 18:52
I believe the problem is that the DocuSign SDK depends on the `RestSharpSigned` nuget package which has been obsoleted.  According to the RestSharp GitHub page:

> The RestSharp package is now signed so there is no need to install RestSharp.Signed, which is obsolete from v106.0.0.

The DocuSign nuget package should be updated to depend upon the `RestSharp` package instead.  The latest version is currently 106.6.10.  Perhaps DocuSign should require v106.0.0 or higher?  My guess is that there are some breaking changes that will need to be fixed in the DocuSign SDK to work with v106 (which explains the method not found error).

**Comment by LarryKlugerDS** [comment] 2019-08-05 07:37
Thank you @mattscully, I have filed internal DS ticket DCM-3465 to have the library updated.

**Comment by RajRele** [comment] 2019-08-21 18:37
We have upgraded restsharp dependency with https://www.nuget.org/packages/DocuSign.eSign.dll/4.1.0-rc

**Comment by LarryKlugerDS** [comment] 2019-09-02 09:13
@all, please try the RC (release candidate) of the SDK: v4.1.0-rc to check that the issue has been solved for you. Thank you.

**Comment by RajRele** [comment] 2019-09-23 21:40
Resolved with https://www.nuget.org/packages/DocuSign.eSign.dll/4.1.0

**Closed by RajRele** 2019-09-23 21:40 UTC
Labels: DCM-3465, answered, question, resolved, v4.1.0, v4.1.0-rc
