### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by mitchdowd** [docusign/docusign-csharp-client#118] opened 2017-02-02 00:31 UTC
Currently the full .NET framework is required to use this client SDK.  Could plans be made to provide a .NET Core build for newer / cross-platform projects?

**Comment by FanMix** [comment] 2017-04-04 08:54
I'm also need the .NET Core SDK for AWS Lambda support.

**Comment by LarryKlugerDS** [comment] 2017-04-04 16:54
(I work for DocuSign.) We do plan to support it. Next steps: We'll be starting an investigation of supporting .Net Core in the next couple of weeks. Then we'll know what's required to support .Net Core and plan our engineering accordingly.

In the meantime, if either of you or other developers would like to test the current C# SDK with .Net Core and let us know what works or doesn't work, that would be appreciated.

**Comment by mitchdowd** [comment] 2017-04-06 01:17
Did some messing around this morning with it and came up with this:  https://github.com/mitchdowd/docusign-csharp-client

Should just be able to open DocuSign.sln in VS2017 and build it.  Got all of the tests except for the auth tests going fine.  The auth ones need a bit more refactoring due to their use of WebApp and WebClient which don't exist in .NET Core, but the actual API code was pretty easy to port.

**Comment by LarryKlugerDS** [comment] 2017-04-06 05:34
Thank you @mitchdowd! This SO seems relevant: http://stackoverflow.com/questions/30227219/how-to-use-webclient-with-netcore

**Comment by RonaldSwaine** [comment] 2017-07-13 14:18
Updating to RestSharp.Core, and changing out the older sync requests with inline async stuff works great for us: https://github.com/RonaldSwaine/Docusign.Core

**Comment by moraleslos** [comment] 2017-11-14 15:47
@LarryKlugerDS Is there another branch, like an alpha version, for eSign and .NET Core?  I tried the current version (2.1.8) and it fails using Login (getting a **"Error calling Login: Operation is not supported on this platform."** message).  The error tells me it's not compatible with .net core.  I also looked at @mitchdowd's code but it's a bit outdated.

**Comment by larrykluger** [comment] 2017-11-15 11:09
Hi @moraleslos,

Thank you for using DocuSign. The DocuSign engineers responsible for the C# SDK receive copies of the issue updates. They'll need to respond, I don't have up to date information.

Thanks,
Larry

**Comment by samarth202** [comment] 2018-01-12 18:19
Any update on this ?

**Comment by matiasgrodriguez** [comment] 2018-01-24 18:37
Same problem, using DocuSign.NetCore by Mitchell Dowd in the meantime

**Comment by petelopez** [comment] 2018-03-07 00:37
@LarryKlugerDS What is the hold up here? Someone went through the work to get a pull request in. Feedback on #154 would be great if there is something wrong with it. If there isn't please accept it and publish .NET Standard version of the binary.

**Comment by LarryKlugerDS** [comment] 2018-03-07 06:12
Hi @petelopez,

I do regret the delay. Here's the scoop--the issue is twofold:

1. **The PR can't be directly merged:** The DocuSign C# SDK is created programmatically using a modified version of the Swagger CodeGen project. So, unfortunately, updates via Pull Requests can't, *per se*, be accepted. Instead the engineering group needs to fold the changes into the Swagger CodeGen software, ensure that the resulting output is correct, write additional tests as necessary, and go through our release process.

    Despite the above, PRs are still incredibly helpful and we very much appreciate the time and effort involved in providing them. They show us exactly what the issue is and a proposed fix.

1. The engineering group responsible for the SDKs is small and a lot of non-SDK work is also on their plate. This issue is on their list to be accomplished, but there are competing priorities for their time. We realize the importance of the C# SDK and are looking at different techniques for improving the situation.

Because of the first issue, we can't just accept the PR--a different PR needs to be written against the CodeGen software. Because of the second issue we can't jump on the problem as fast as you (and I) would like.

To help with the prioritization, please ask your DocuSign Account Manager (or any DocuSign contact) to add your interest in this issue to the DocuSign internal tracking system. It is item **DCM-2161**. (This request applies to everyone interested in this issue.)

Additional information on your use case for the C# SDK would be helpful. You can also write me via  apihelp@docusign.com  

Thanks,
Larry Kluger
DocuSign

**Comment by petelopez** [comment] 2018-03-07 06:31
Thanks @LarryKlugerDS! This very helpful and I’ll be sure to follow up and provide feedback to the appropriate parties.

We’re all resource bound and it’s tough to manage OSS projects. If there’s more we can do please publish how we can help.

**Comment by DavidRouyer** [comment] 2018-03-09 11:29
@LarryKlugerDS If your engineering group is small (it shouldn't), why don't you just drop your current modified version of Swagger CodeGen?

- You could accept PRs
- The open source community could fix issues, improve performance and add features at a much faster pace
- You could concentrate on fixing issues instead of fixing your custom Swagger

**Comment by LarryKlugerDS** [comment] 2018-03-09 12:08
Hi David,

Yes, I'm suggesting that idea too and it will be considered by the team. 

Thank you for your work with the SDK and the PR.

Regards,

Larry

**Comment by broomandan** [comment] 2018-03-28 15:50
Hello @mitchdowd and @larrykluger,
I have looked into @mitchdowd fork but ApiClient.cs class doesn't seem to have jwt authentication methods such as ```ConfigureJwtAuthorizationFlow``` Any thoughts? Am I missing something?

**Comment by mbirtwistle** [comment] 2018-04-05 09:05
Any ETA on this? I'm in the same situation as @broomandan

**Comment by gswartz777** [comment] 2018-04-19 15:46
@mitchdowd when I try to use your fork of it I get the following error when calling the apiclient.GetOAuthToken method.

`System.InvalidOperationException: 'Misused header name. Make sure request headers are used with HttpRequestMessage, response headers with HttpResponseMessage, and content headers with HttpContent objects.`

It's failing on line 537 in the ApiClient.cs class
`
webClient.DefaultRequestHeaders.Add("Content-Type", "application/x-www-form-urlencoded");`

Are you still able to run your code successfully?  Not sure what is going wrong.

**Comment by DavidRouyer** [comment] 2018-04-19 16:00
If you have an issue with the fork of someone else, don't report it here.
My [branch](https://github.com/docusign/docusign-csharp-client/pull/154) works like a charm.

**Comment by gswartz777** [comment] 2018-04-19 16:41
I would have reported it there, but there is no Issues tab to use to report it.  Does your branch work with .net core?

**Comment by DavidRouyer** [comment] 2018-04-19 16:53
This is why I made it, I run it in production and the full suite of tests is passing. If you have a problem with it, report it on the pull request.

**Comment by RajRele** [comment] 2018-08-07 21:25
@all We have recently released a .Net Core / Standard 2.0 version, please have a look. and open a new issue if you have any concerns. I am closing this issue.

**Closed by RajRele** 2018-08-07 21:25 UTC
Labels: Area:Net Core, resolved
