### ISSUE TITLE
Questions for uploading the logo for brand

### ISSUE THREAD

**Issue by MariusDing-InfoTrack** [docusign/docusign-csharp-client#202] opened 2018-09-11 05:56 UTC
Hi,

Can I ask how to upload the logo for a brand?

I can't find the place where I can pass in the logo (http path or byte array) in `CreateBrandAsync` function.

Please help me.

Regards,
Marius Ding

**Comment by MariusDing-InfoTrack** [comment] 2018-09-11 12:16
@RajRele 
Hi RajRele,
I try to pass the Base64 string to `BrandLogos`
```
var brand = new Brand()
            {
                Logos = new BrandLogos()
                {
                    Primary = fileBytes
                },
                Colors = new List<NameValue>() {
                    new NameValue()
                    {
                        Name = "buttonPrimaryBackground",
                        OriginalValue = "#e2e2e2",
                        Value = "#e2e2e2"
                    }
                },
                BrandName = "hahah"
            };

var response = await accountApi.CreateBrandAsync(account.AccountId, brand);
```

Brand got created and color can be set up. However, I don't know how to upload the logo file...

Please help~~~

Regards,
Marius

**Comment by Satharon** [comment] 2018-09-11 17:11
Hi,

Thank you for reaching out. I did some testing on my side, it looks like the logo needs to be converted into a base64String. You can use something like this for the conversion:

using (Image image = Image.FromFile(@"FILEPATH"))
            {
                using (MemoryStream m = new MemoryStream())
                {
                    image.Save(m, image.RawFormat);
                    byte[] imageBytes = m.ToArray();
                    string base64String = Convert.ToBase64String(imageBytes);
                }
            }

Then set the logo to base64String.

Regards,
Matt

**Comment by MariusDing-InfoTrack** [comment] 2018-09-13 00:15
@Satharon @RajRele 

Thanks for helping Matt~

Currently, the project I working on is ASP.NET CORE.

```
            byte[] imageBytes = System.IO.File.ReadAllBytes(@"C:\Users\marius.ding\Pictures\backgroud\google-new-logo.png");
            string base64String = Convert.ToBase64String(imageBytes);

            var brand = new Brand()
            {
                Colors = new List<NameValue>()
                {
                    new NameValue()
                    {
                        Name = "buttonPrimaryBackground",
                        OriginalValue = "#e2e2e2",
                        Value = "#e2e2e2"
                    }
                },
                BrandName = "haffh",
                Logos = new BrandLogos()
                {
                    Primary = base64String
                }
            };

            var response = await accountApi.CreateBrandAsync(account.AccountId, brand);
```
I tried several times. The brand can be created however logo didn't get upload.

Can I ask if it works on your side?

Regards,
Marius

**Comment by MariusDing-InfoTrack** [comment] 2018-09-13 00:56
I tried to pass the base64 string via Postman as well.

I got the same response.

The brand can be created successfully. However the logo never gets upload.

The request as follow:
{"brandName":"haffh","colors":[{"name":"buttonPrimaryBackground","originalValue":"#e2e2e2","value":"#e2e2e2"}],"logos":{"primary":"iVBORw0KGgoAAAANSUhEUgAAAQQAAADXCAIAAABzt7hoAAAbpklEQVR42u2dh18U59bH+Uve95bcxDcCgtKXpYMivRdNLBhjTI9JrprYBew3lhs1iSa0pShBLHQRRQFBwUIRGyq6FXZntu/Mzuz7DCTGGAuwzO7s7Pl9ziefmCju7DzfOe15zrhYQCDQmFzgKwCBAAYQCGAAgQAGEAhgAIEABhAIYACBAAYQCGAAgQAGEAhgAIEABhAIYACBAAYQCGAAgQAGEAhgAIEABhAIYACBAAYQCGAAgQAGEAhgAIEABhAIYACBAAYQCGAAgQAGEAhgAL1UlFZjlknJ+3dN17qNF88bGmt1p6q0FSJteclfTVddqa87bWhtMV3tIu8MmqUSWo1bKAq+RoDBIWWWS9G6158+oT68H8vdoFz1kSJnoSI7WZ4eL0uaJ4uLkM4PlUYFSaOEL7D5obLYcPTb5KlxiqxkxZKs0c8+UG1Yo963C/Fj6uwwDz+kTSb4kgEGDgPw5ImhsQ7bs2300xWKrERpdAiz3CMEjIUH/PbPqVnEuAkYVOaFyJOiR1YsxjZ/o/u1grg9YDGT8OUDDJyQ6eY1zQ8HRpa/i1aqRDBbEuQlDfaRhvn/hgEbhvAI9ZMEeTN/XaivIjsJ27bJeLGF0mngdgAMdhAxOKA5ckixMAWtfrG/O1qa7ALwcpME+4gDPCQCD1liFArJjO0XLQQEUQADu1kwRRv05IMhbVnRyNJsaZC32MdVEuzNPKcjA+2CwR82/gFCfMV+syS+bvKMBPXBfeStflqns5jNcOsAhmkTbTabJWJDa4tq87cotRX7uUsC53CCgRdSgT5YsDeiQhopUH79qb7uNJNwg68AGKxOis3k3dvayvLRT5YzAUmAB3r6cg6AlxnKKwI8URCF8hlN0VGiv9dCEHBLAYYpZQX9vepD+5iIKMxfEjjbXimB9dm2ROiFwjnFghT1/t2m690WmoabCzBMVOTQPfX+PYqFaQwGwT6/FUYd2hASTI3LT5GVhH+3g7x3B+4ywPC6JFmr0RT+pMhO+qMt4OgYPE8F49/kmQmaX36gtVq44wDDi2Vsa1W8kyZFybGDRkSTchSC2YpFGaauDlj3AMOfHYIGx7Ztlgg8mHYBB2tE7NSdJEFeCAn1nu20XgerH2Cw0CRhaG6UJ8wT+7o5BQN/MbGPmzw11tjZAds6nBgGs9n8+BG2Y8tvGyicxCG82EV4o3/RHN5PKeRQa3I6GGijwdByduS9d35rnzknBs9amL9E6DW66iNTz1XYLu5EMFA4pjl6SJYQhW4/kPCnrDpwjjw7WX+mGjZxOAUMZqlYte7r8Z08AMALtv0FectiwtTf76VJEmDgs0xXuxSLMiQIA3AIrwyZkKnWfkkplQADP6U7XSWNFEpD/WC5T9BFKDITyAf3AQa+SSsqHMsQ/GGVT8KCfeTJ0aaeKwADbypHtLa0UBoWAKHRVI7URQkNF5oBBl6AoNdpjhwaD4JhcU/OQnzlCXOZc3MQJvGBBK1W8/MP4zv7YXFPLmEQeskzE01d7ZBA84IEk0lz9DBzX6GEOlkSBLMV76YTN69DaZUvGXNJAUqXgYRJkxDgObIkm7hxzeLc4g8Musqy8XkqsLgn6xNGlmSZEAlOv0OJJzDoTlVJQn0hY560BXkx0VHvddibxBMYjJ0drM/w4qWF+ikyEoib1wADnsBglorlGfEQHU1h/4U8PgpOvfEHBlqNK7/8hOvb7/40PvV1v81WPkEWF2m83A4A8AQGWq9Xf7+Xoz3msLGiFkpj0LKLEspiwmXJ0YoFKSNLskfeXzyyYskfhn65dAH6X/KUGFlsuHRuMBPvhfqN/XE/Vq4uyFuRHm+83Aarny8wmM36+hpmzjunAiS0iIVezI7o6FD5wlTllx/jO7Zqi47q604b2y8S/b3kwyGzQk6NKJ4a+iX56CEx0GvqbDc01mpLi/C9O5XffKlYmo0e3sjpMdurps/1jfcTmElKIL7AQJN3b48szR4/u8iRIzKSwNno0T766Qr1wX2GpnpT7w1KLrNM4YQATVOYirh9y9Daoi08olzzuTw5evznM07DiqOqTD9h6QKi/yase/7AgAIkbMs6idDepzfHhpxKAjzEgtkjOQs0Px009Vw1S8S0wTBtl0oSlEJO9N3UHSsd/WQFM2bY310a5jcFJBgSchYwVVQQn2DQn6m2fy11DAMEpHL1Z4ZLFyiVkmGApb4VTdOEicIw040ebOt6lIhL/D0m9SBAjmVkSRbRewP6CbyCgcKU0tgIBga7HoJBobxq9RdMyGHjxi1Nk0N3VRtXS4K9JxolhviiBB2lJbDc+QYDlrdR7OtuxykvCAPFO2mGc0323b9gvHgepcJMev3afkLyfNO1q7DW+QYDCkjEKEKwX8FUNi9YfWgfrePExFKmuHxgj2xu0EtP84X6yeMjmWFhIJ7BQOGYIjPRPhWkUD9plFC56kMObu00dXWMfLSMSSHC/J4/wJkaa+yCzhofYVAf3Mu8OsTGARJKlIO85GlxutJC2mjg7GNCvX+PLCZM+vuTQhI41k+A6IiXMJB3bzMtNhuf7g/zRySMfpjjACchCUJ/6oQ8PZ7p+gV4MFXUwX5Y3zyEgSYtWO5mZneDrV/24avasMZhXvNhNhsvXVBkJTEk9EFnjacwkPc75BnR0mDbVo1CfLCduZRy1JFOvZjJsU0f96GfwFMYaIIa+MpQ5CpP8ZUIhdJIm7SWhV74gT0wsR1g4BgLqk7yQhjR8rapxnV0qY84MFAazjIJAk9sVx4sDoCBc+kCdWcP0fA20eBKNLuR512xdXOkYQLGWIqOAmer1v8bVgbAwD0WNLfI9gSi/k2i0Y2xJjey1VW730Oe7MfwED7tVVRv1aY1cDQeYOCkWxgWEQ3/RzTM/A2GcTvnpi+aNbJsbHtS2DT6hDnKrz6lDXpYFgAD92QaMXcvI+r++ScSfufBeMINWz1HOjdAGjo9JIwsW0gO3YM1ATBw0S/QysvEWU/GM/wVBmTNbqY6N/UuT1m8nyTIqra0JNhHljTP2NYKFUmAgZssmKk7O4jav72YhN9TCGT6IndFlq8kMHDKbWZpuL+28AhNmGBBAAycFKkjW8OJujdfBcPvLoKoc1WtmiMRBE4lhQjxVX79GTUyAqsBYOCqYxi9QNT9g6movhaGcRdx3lWz3ZPZvBkyuQqSLCna2HEJlgKIuzBQAxuImv8lGt0nBMO4tbhpD82Sx/tNgofwAGznVlgHIA7DQBmI8wKi/q1JkPA7D4ZS99GlY1XX8NeTIM9KND96COsAxF0Y6JEWou7vE42R/mxki6vxpJvqKy9ZdMBrUgihl7bkF1gEIE7DYB5YP+kY6c9dCFODm3rHbFmCvyQ48GWbUuWZiRSOwSIAcRgGykheippKjPSsnXUjml31P88aXewj+evevshASYCntuoYrAAQt2HQ9BENiISZVsEwXmJqdjNWu2Fr50hQSo0s8pn3EixMpfU6WAEgTsNgfnSEqPmbtST8mQrNd56yaH/peKM6MlDs66YHtwDiPgxkdw5R98Z0wjDWmNMXuCvSfSXByEX4yBKiKD1syANxHQaKbI0gGmZMMwxMVu1qPO42uthX7OWO74SzOyDOw0BrbzOxfsPM6YeBqbq6ETWuyo/diRv2n8lO03w2gGE6/IK8gaj9x9SLqq/PH/5FtsdYSDtXVNFq6X5AXrlPXh3im6GL6nlAkhTAYH32fG8fUfcvtkhAVvt3861NFspo57yIoudux0Nz8Yh8vllILh61DRerKIDBahhufkHUz2ANBlei4S1KVmOh7XyrSLMFwRCWx0MYIvJwwSYMuQiAwcrogTB3vfPS0zzWW/1b5PlgWjNg/4qZ2RK9Aw/PZx6iPLO523Df9dipHhPAYJ1MMrJtPkvZM2N1b5BXFtFGCcDAKgz+G7HvGw0Ag3XS3SXPB7KYMNT9yzyYZzFrAQZWLXAzvrZcDzBYFyWprhLNvmwmDDOo4RK7Jwy8hyE4F8/5QQMwWAeDrJY468UWDA1vE81zaHkdF66U3zCE5uJp+9Q0wGBVk2FYRJydzVr2PIO8EEarugEGti0sD4/fjat0NMBgBQxDh4gmDxZLSW3xXCgl8R6GiHwmjX40YgYYrGgy3N1DNLmz6Bm6smn9EMBgAxhQpDTwBGCwBobBfBY3YiAYet6njVKAgW2LzMeFm7GeByTAYAUMt/JZrKvWzzDf+MJCYACDDcx3PdY6SAAMXIZhld236DkDDChh8FmnahkAGKyBYWAryzB8aSFxgAFgcAjPkMcuDDe/spBqgAFggDBp3DNAmGQjGM71Awxc9gzXP7cQKoDBNjCc7QMYrCqtbmO3tNq9nAtbVp0EhvMQJlkFw73viKZZLMLQmUnr7gMMkDM4AAwsb8eYQbbF0ep+gIF1GLbj3gCDtTA8LmNxo17DDPJCCK26AjDYoAMt2IR13oMOtBWiZfVsbuGeSTTPpmU1AIMNYAjagl1/BDBYA4Oqm/XDPY+KLLQZYGB7o154Hn5HChv1rJHuHnlByOaxzzfMA5u40HfjNwyIhPk7cQlGAQxWiFCQbbHMkTT2BgJ0LaANYoCB3cM9uXjif3Cdg+XPnBsVQ5qvLCLq2RsVM4NoCaTVfWMj7QAGtiwkF88+oLZYAAYrWw29X1n7mpJXpw31b1KSk3ZPG3g+EGAL/kmBDmCwGoahg6yOlzTV/t3Sv8b+4yV5DYNgE7b9NIyKsb7VoDjH6uBhS8MbWOs8gsDtDkPUdiacQLmmXYzV9rPfBlXxJSPAYHXWoLtPnJ3F0lA9S9PMvtrZSaKodvE1O8NA0Un/UcfsZKZI2N4SduPzduCRrPHgtwFrGYBZq9OSRLdGTfvLSkhEQuPM82d8YsuT3iqI29i+nwtXajf3S1nePageH5fNRpMhLA+/5WjTACwcfY3V9ZXT/hordaN78UlhYGmqlyjDtyQltHyh0oBbnFUSjArNxSJZq6vG7VZrDDTAMB3PrcfFRO3fpssh0I2uT+o9NldFeJZm+JRmCErTBaUZrgUxR3uPOy0MJ6+aAjdj7JWScn7UOuLXwslX3+ruEI1vW//qW6rRlW6c2Vbjk3M8ZpYo0680I6A0fdy8S5Jiq5ZjRo1zwrC2QidkDYaATVjeST3AMG1ZAzOYvv5NK3NlTYPbkeqguWXJnqLMpxiMG3IOHkVxzukc1AYa5dARrFV1AzZixy4bAYZpEzNNrOZ/plZgJcdIGK73+KYySlCW5iPKeI6EcfMRpc6rXKrQK50NhtrrRNAWdrfoXblPAgzT5xuUHUTdP4kG16mRcKXGa/GxWJQe+L8Ig6c2pyTxQE+hs8GwqlgXmssWDOgnp+xVO9wWPU7DYKFpsjWUqJt0pEQ3zTx5KiCiLNn7JQ7hOYuqXDyovO88JPQ/Mc/foWbzNSXYmnIdrqcBhmmtKd3aStT878QjJTPKmJtcf6wO8hale5dOiARk/qL0DW37nAeG7+r0rLafAzdhR1uMBgJgmF7foGpnug0Ti5ToRle8wX1NZaSrKMt3wiQwMJSmRR5ffPZhO22heU/CoxFq4fcaFs/05OFzt6kvDhIUvBR9upNoPdkW89pNe2Sjq6nRrbPGK70iHpEwcQz+yKRLUpY3fjuskfCbBNJsOXzWMHc7my/s2YovOqQZklMO+hVxGAbaTN3b9+rum6XRVdngVnRSGFSW4inKFEyehLFIKc1XlLK3u8BAGnkMQ99j8zsHNRFs7pMN2oJtPaHHdDTAwEISjXUTzd4vPOszXjW6X+e5qSqCebqPtZYDpmrIOYRVvFM7dIGiKV6SoDXSu88w2UIkm0MA0D8rO01mh/0KXTj96Qil+frHRN0//porWxpndtR4v3csxq803W8yScLLzKs4KbH6g77Ru/wjAUXwzf1E3G41q6lzWB6e/V/1jUdmx/2iuA0DipTElcy+jGd2dDMkNLkeOyWIKU/ye10nYVI2pzjpndqv1CYtz2B4rKSW/agJyWX53HMe/k2FDtPTAANrOOjuk53p41szTGNJgqXp7byqMO9pcgjPmWdRwrKGb0iK5BMM64/rhJtZHpS0DY/egZd1OHbS5cL5T0hR9w4g52BiMJipaHBfdmy+W0n2tGPwdM/SrMKYj5o38oaEkotG/w0q1qeGbUMxkuaW2AwwsOwcsG6yNcrSMKPzjNe88kT3kkwBOyQ85cG9IHZd216advjOQ1MfEbAJi7TBSet8HPkfR68+OAAMFpo0DmwsPhXoL0rzKmWXhKc8zC5KWH9p76hB5aD31UTS9TdMYbnsHnd+atE78cZewtGfHS4O8SnvjQxEV73vyz4Gz5p3SfK/L+x4qBY7Igmnuk3jG0htMz8PJei4gQYYbCGStuzo+gmtTlvCgBwR+htXNm3olvU70B3VGumydmM8y4XUZ024BS9t40O/0sVRPuhjjXReZY6vKNWmPJSmeRUnpZ365PS9cw7xLY1q6X31hphdeIStJjKF5eFJ/1ErtTTAYFMd7a1Eqa2AhYrqBPrTC3ddPaIhOD0l7rbE8nWpbvyEjc1eSuK/ES9q5ck2FkeCwUQRmac/m12cYGMYniKRevKj1idXuPnlnLx1LWXvaHiuIWobZrPJeaFb8fR9aiNBAwx20FVZn0dRPIrm7cODKBWhuKXjvyojh8bMPFA/+eTcllkF8YIjmyJ3Po7KN9rsxW2+67FTPSYLX+TicJ849/JBt4IYgT1geNqljj+xAmURJrOdi4laQnfoeilKbDwK4wRl6QFliYEFX0Ts6Y3K19ti1PZWZjOSmaIBBrtJY9IlnvgA5bUB9uMB/e2eRfHLG79tHm4fNWCEDbdv0BbaQBofa6SiW6eSTq6cVRjrJ0r949FQliAoWRq2ryly+2jUNhaPd0bmM/ORHO4VhnyDAanp4SV0431FKXbkgXkeF8UjL5HTsPbYYN0d1QPcxO4UJjNNyfWjKFDc31OUWP3BrMK4Fz0RMgLKmP8YfKggcoc0Kl/HEhLCzfjqMq2BVyw4Jgzo0bi964c5xYloRdqRh7HpG2meY0gkVa/c3H6g5n7LLeV97bQWnRADyA90SK4X9ld93pIbcWwRgtCrOPFVn60sBbkI4ZH88D035+ajlFoz7QMkE/aorw6RNA0wcCFrxB/n1K+Z/eo1YTtj2hEIzuDy7Kwzn6+9uKegr+r8cOdDtdhETeXhSVKkWCvvkFyrGKzd3vkjiseif80ZS98TfSbaeUxDPAQWrQzdXxOVrx3LIrDpCpBQtnCwyWAg+HZq3FFhoGgKrbb5aImUpHCDB8ZQ+I4+j68oVViWNbdyafaZzz88uzH/8qFf+ipP329uF/f0j94d1kjQk/6JVoqWO/oXZPewh92yvnPDHb/eafjpZkX+5cOfnNuysGZVTNV7iC4/URrzM0tSpnJyoyxFULIw5PCPUdsV01VlQiSsOKp13IPOPIQBCaWtR3uPC8oy/DkDwzMZRfqzIZygNAPhEX7s3bmVS9ASj33G0C/RUz/y+KLQioWBZZljLcWMp2nJdMSB6CdkCn/eGLHrTlSeyfqBeXG78PobBMXHWSIuDv3pSdr87ws7fEXJAdzjgVtWlhRY9EH4fy5HMSmEVTDsPK3n61QdF0e/AIVemVy90r6VJUfhIUC0IHRf/RgP6qmR8O4hjRTj58wEPsCA1CMfCKlYADxMgIdklFUHH/wlaptyaiWm9jukhb9y4cdlND9qRzG3jfd4O6al+VfMFx7dGL67PypfM0Ekxo9GlFzi81wp/sCAVD/UinjwKkkSwIp/rZXHCYrfC91fz9Rbmcbca2qpQZvx7+r0Fr7LhU8Xc/LuWWF5llcx8DChFEJQsjD48JHIHU9enVULNmF51XqdkQYYHKzYWjFYKyzLsu/OJcex1IDSjKAjWyN29b+MB/+N2Opy3aiG/yTwDQbL2E6NisEaxAOnmnFcTiGQBRZ+FPbdpbGunPq5+fKfFmofjVAW55AL/y6JpunywTOC0gw/254RdeSQCT04UkO+PxaVRz5NqYO24Dk/aIbkZovTyIWvF1Z+qwbxYN+dfA5WZSqPDf5hbySTUuvDcrEF/9X0DjsRCXyGAanqToO/KN1PBDxMvMo0P7Dg87Cdg9kH9FfvkxYnkwu/L6/5UXvcieU+omR/QGJiL/XyKY3NPLm6T6yzOJ9ceH+F/aN3V57d6FOSDC3qVxv6fryKkz9oXD+oumtxSrk4w0WOGFQ7u34SlmfO4cr5B24ZSq68ipNQPLmt87BUN2JxVrk4yXVqCf3x23WxVcs9i+Ihq37OPIriIo4tKhs8oyP1FieWi/NcqslM9Mj6329c51mU4FcKVdffRmjOKozLOvNZ25Nuuw/7ABhs24Kw0BpCt7+n0Lsk2as40fbD+TiWJDDnSNde3P1EK6Np2uL0cnHOy24X96CQyb0wJkDkvEmCsCyrpP8kBRg4OQyWsY0bO7p+9C5J8i52ro3ffqJUj8K4zNOf9Y3cAQAAhj/ULev/8OymoLFz97xPrMczpYQTK4r7q8EhAAwvdhGVdxpy6tcIy7NQLsHL9pzv2MyO+BPv7+r6aVgtgZsOMLxKTzSyov4TCAkURXgWxY/NbORDeo3wnlOcGPPrsrzLB69Ke+FGAwwT1QP8cfngmRVN61FEgdJrB21aj59tmlOU6F4YO+/XnJ1dP3WIrzl5DwFgmIrMNCXVKc4Nd3x5YVtgWaZ7QQxKsh2oTMTkx0Vxswpj0059fOh62cDoPS0BGAAMVoiiKbSG0EradeVIdOVSt8KY2cUJKJ3gcuyEIiI3Bt3k5Y3raofOq01a6KMBDNMszKg+da95acNqFDW5/jLfqyRpjAquREQ+ohTPwniEQVzV8l1Xjt5S3oMOGsDAuu5ij37uq8w+87mfiJlHj57B9trW4V+a5lOSjJyVZ1ECygrWtO6+8LhLSxjgHgEMttagcqi4v/qLlryEEyuCy7OZea8i5jDA+HTU6e1XPP2Z44bitKDyrOhfc5Y3fLu3u6BTcl1L6OCOAAz2l0KvbHvSfeTmsfVte5c1rE2s/mBu5dKg8uyxRi/z8Ebew4exFBRi+YpS/V5ivowxo7bR7/Rm/lQS+lPMGe6ydPTToiqXJFWvXFy3GnmAg9dEZx+2PdKI4csHGLgrpQFHHuP8cGfFYM3310o2dxz47NxWRMiCmlXJJz+MrXoPremQioXBFQuet/IF4ccXoYd9QvWKtFMfL6r7ekXjuq/Ob8+7fOjw9dKKwdpzwx23VQ9G9CraAskAwOCA0puNCA+xVnZH9eC64lan5MbFJ1fOPmpvetj2V0MItYt7umV9vSO3h/BhmW4EM2mgFgQwgEAAAwgEMIBAAAMIBDCAQAADCAQwgEAAAwgEMIBAAAMIBDCAQAADCAQwgEAAAwgEMIBAAAMIBDCAQAADCAQwgEAAAwgEMIBAIIABBAIYQCCAAQQCGEAggAEEAhhAIIABBJq0/h/rTP/aXuQlwQAAAABJRU5ErkJggg=="}}

The response I got back:
{
    "brands": [
        {
            "brandId": "65c98f59-7ed5-4d86-b5b9-a79838650c89",
            "brandName": "haffh",
            "colors": [
                {
                    "name": "buttonPrimaryBackground",
                    "value": "#e2e2e2"
                }
            ]
        }
    ]
}

You will see the logo is missing.

**Comment by Andyhacool** [comment] 2018-09-27 00:58
@MariusDing-InfoTrack  Hi Marius
I had a same issue and writing this for the future reference. 
There is no support for uploading logo in C# Docusign SDK yet, but you can still do it via the plain REST API call. 
Here: https://developers.docusign.com/esign-rest-api/reference/Accounts/AccountBrands/updateLogo
You can attach the image as binary format. 
Have fun!

**Comment by conficient** [comment] 2018-10-03 08:38
So this is closed as "Broken, won't fix" I guess.

The issue is that the DocuSign REST API is malformed. It does not correctly specify that the request can contain a body content. If you look at the API documentation there is nothing in that `updateLogo` page that mentions the body is used or required.

Because all the DocuSign APIs are generated off the REST API definitions, this means the code generated is also wrong. I used to think DocuSign's API was good but now we're evaluating Adobe Sign as we can get a lower cost there.

**Comment by conficient** [comment] 2018-10-03 09:28
Thanks for the feedback @LarryKlugerDS 

Sorry I was a bit salty but my bug report #153 was 2017 and this is the first time anyone at DS has responded. The API is great _where it works_ but the broken bits are frustrating because we then have to write manual workarounds, which takes extra time and resource.

I'll forward the request to our support.

**Comment by LarryKlugerDS** [comment] 2018-10-03 09:37
Thank you @conficient, no worries. I certainly understand your frustration. 

I very much appreciate your use of DocuSign and the SDK despite the bumps in the road. We are working on them.

**Comment by RajRele** [comment] 2019-02-18 22:05
This is resolved with  3.1.4-rc version published on NuGet Store. [Download Link](https://www.nuget.org/packages/DocuSign.eSign.dll/3.1.4-rc).
We will open source and release a stable version within 2-weeks. In the meantime, feel free to try v3.1.4-rc

**Comment by conficient** [comment] 2019-02-19 15:44
> This is resolved with 3.1.4-rc version published on NuGet Store. [Download Link](https://www.nuget.org/packages/DocuSign.eSign.dll/3.1.4-rc).
> We will open source and release a stable version within 2-weeks. In the meantime, feel free to try v3.1.4-rc

Many thanks, I've started having a look at this.

**Comment by RajRele** [comment] 2019-02-25 23:24
Stable Release version published on NuGet Store. [v3.1.4](https://www.nuget.org/packages/DocuSign.eSign.dll/3.1.4)
Release https://github.com/docusign/docusign-csharp-client/releases/tag/v3.1.4

**Comment by RajRele** [comment] 2019-03-08 22:49
Closing this issue as resolved!

**Closed by RajRele** 2019-03-08 22:49 UTC
Labels: DCM-2855, answered, question, resolved, v3.1.4, v3.1.4-rc
