### ISSUE TITLE
Intermittent issue while using Sandbox Account while trying to send envelope for remote signature

### ISSUE THREAD

**Issue by manishandankar** [docusign/docusign-csharp-client#240] opened 2019-09-10 15:10 UTC
I get intermittent error message while trying to send the envelope for remote signing: "Error while requesting server, received a non successful HTTP code Error with response Body: ". 

Then I rebuild the project and try after 10 mins. Don't know which of these two activities help, but then it starts working fine. 

I am using the Sandbox Account. Is this issue only with the sandbox account.. What am I missing?

**Comment by krishnamhn009** [comment] 2019-09-10 15:34
This is something you should ask on stackoverflow.It's most likely issue with integration key.What's status code you received?

**Comment by manishandankar** [comment] 2019-09-10 22:07
![2019-09-11_3-33-42](https://user-images.githubusercontent.com/29952952/64653902-537c5580-d445-11e9-90e7-6f997c2efe0e.jpg)

The Error Code is 0 and the Message is "Error while requesting server, received a non successful HTTP code Error with response Body: ". No other clue.

**Comment by manishandankar** [comment] 2019-09-10 22:14
I also realized that rebuilding the project was not a factor. This time I just waited for a few minutes. Interesting to know what could be an issue with the integration key? I would see if a new integration key would help.

**Comment by krishnamhn009** [comment] 2019-09-11 07:12
The error code indicates that the response was empty as not even headers were returned. It means connection was accepted and then closed gracefully. There are a number of things which could cause this, but based off of your description,seems network was slow.

**Comment by RajRele** [comment] 2019-09-26 21:26
Are you still facing this issue? can add a little bit about your project, is it dotnet core OR framework 4.6.1 ?

**Comment by LarryKlugerDS** [comment] 2019-10-06 05:33
Closing due to lack of updates. Please re-open if the issue is still active.
Thank you,
Larry

**Closed by LarryKlugerDS** 2019-10-06 05:33 UTC
Labels: answered, question
