### ISSUE TITLE
resend_envelope functionality

### ISSUE THREAD

**Issue by ckropf** [docusign/docusign-csharp-client#89] opened 2016-04-12 16:46 UTC
I am in the process of developing an integration using this client and am trying to integrate "resend" functionality. As I understand from this stackoverflow post (https://stackoverflow.com/questions/17725827/does-correctandresendenvelope-soap-api-now-support-for-rest-api/17728580#17728580), as well as the DocuSign REST API Guide version 2 (page 157), the right way to do this is to send a PUT request, with a serialized Recipients object containing the recipient that needs the resend, to: https://{server}/restapi/{apiVersion}/accounts/{accountId}/envelopes/{envelopeId}/recipients?resend_envelope=true

However, in searching the csharp client, I only find the "resend_envelope" option available via the EnvelopesApi.UpdateOptions object, which can only be passed to the EnvelopesApi.UpdateWithHttpInfo method (and its corresponding Async). That method defines the URL template as:
"/v2/accounts/{accountId}/envelopes/{envelopeId}", not "/v2/accounts/{accountId}/envelopes/{envelopeId}/**recipients**"

And indeed when I call the UpdateWithHttpInfo() method, passing an UpdateOptions object with resendEnvelope = "true", I see that the client makes a call to:
PUT https://demo.docusign.net/restapi/v2/accounts/{accountId}/envelopes/{envelopeId}?resend_envelope=true

The server then responds with a 400 and the following error:

{
  "errorCode": "INVALID_REQUEST_PARAMETER",
  "message": "The request contained at least one invalid parameter. Value for 'purgeState' must be 'documents_queued' or 'documents_and_metadata_queued'."
}

This I assume is because it's sending the Envelope, not the Recipient info (which of course is because I'm calling EnvelopesApi.UpdateWithHttpInfo, which takes in an Envelope, not a Recipient).

Is this a bug in the csharp client? Should the method(s) that takes in the EnvelopesApi.UpdateOptions be hitting https://{server}/restapi/{apiVersion}/accounts/{accountId}/envelopes/{envelopeId}/**recipients** and te taking in a Recipients object instead of an Envelope object?

Is there some other way to do this?

**Comment by ckropf** [comment] 2016-04-12 21:23
After looking at this a bit more, it appears that if EnvelopesApi.UpdateRecipientsWithHttpInfo had a fourth optional parameter (as EnvelopesApi.UpdateWithHttpInfo does), and if UpdateRecipientsWithHttpInfo were then coded to add the appropriate query parameter when options.resendEnvelope != null, it would work as expected. 

In other words, it seems that this parameter:
`EnvelopesApi.UpdateOptions options = null`

And this section of code:
`if (options != null)
{
	if (options.resendEnvelope != null) queryParams.Add("resend_envelope", Configuration.ApiClient.ParameterToString(options.resendEnvelope)); // query parameter
}
`

should have been put on EnvelopesApi.UpdateRecipientsWithHttpInfo instead of on EnvelopesApi.UpdateWithHttpInfo.

I'm very new to this API and therefore may be overlooking something obvious, but I was able to successfully make a "resend" request through the API after making these changes.

**Comment by nickforce** [comment] 2016-09-20 07:25
I am facing this same issue using the java sdk

**Comment by LarryKlugerDS** [comment] 2016-09-20 07:53
Please accept our apologies for this issue. There was an error in the Swagger file which was used to generate the SDKs. (That's why the problem is the same in the different SDKs.)

The work-around is to make that call to the DocuSign platform outside of the SDK. The next release of the SDKs will solve this problem. Unfortunately I don't have visibility into when that will be.

**Comment by ckropf** [comment] 2016-09-20 13:28
@nickforce, yes, as @LarryKlugerDS suggests, the workaround I went with is to manually call the docusign api endpoint "/v2/accounts/{accountId}/envelopes/{envelopeId}/recipients", passing the "resend_envelope" query string parameter. I essentially took code out of their EnvelopesApi.UpdateRecipientsWithHttpInfo and EnvelopesApi.UpdateWithHttpInfo methods, piecing together the necessary parts from each.

**Comment by nickforce** [comment] 2016-09-20 21:03
@LarryKlugerDS Thank you for your reply, I will look forward to the next release of the SDK to correct this. In the meantime do you have any Java recipe sample you could provide for me to I leverage to implemenr this? I would like to avoid scraping logic out of the SDK if possible. Thanks in advance for your help.

**Comment by LarryKlugerDS** [comment] 2016-09-21 05:42
Hi @nickforce, Here is a [gist](https://gist.github.com/Ergin008/fbc8484731ad755096de) that shows how to make a call to the API. In this case the call is Envelopes: create. 

In your case it would be a POST to  `/v2/accounts/{accountId}/envelopes/{envelopeId}/recipients?resend_envelope=true` 

Regards,
Larry

**Comment by nickforce** [comment] 2016-09-21 14:39
Hi @LarryKlugerDS, Thank you for your help so far! Following your suggestion I am sending a POST to /v2/accounts/{accountId}/envelopes/{envelopeId}/recipients?resend_envelope=true 

I am now getting an error response however. 

here is my JSON response string - 

"signers": [
    {
      "name": "ZELNINO WINTER",
      "email": "myemail@email.com",
      "recipientId": "1",
      "requireIdLookup": "false",
      "routingOrder": "1",
      "status": "error",
      "errorDetails": {
        "errorCode": "CORRECTION_HAS_DUPLICATE_RECIPIENTS",
        "message": "The specified envelope corrections have duplicate recipients."
      }
    }
  ],

**Comment by mmallis87** [comment] 2017-01-25 23:51
@nickforce hard to say why you're getting this error without having an idea about the existing recipient list. Can you share the response of this call: GET https://na2.docusign.net/restapi/v2/accounts/{accountId}/envelopes/{envelopeId}/recipients

more specifically, in your case, the signers array.

**Comment by mmallis87** [comment] 2017-03-06 22:57
@nickforce @ckropf @LarryKlugerDS This will be fixed and shipped with the upcoming release of SDKs. The deadline for this release is March 15th but you might get it few days before.

**Comment by mmallis87** [comment] 2017-03-10 00:56
Fixed in version 2.1.0. See PR #120

**Closed by mmallis87** 2017-03-10 00:56 UTC
